version: "3.2"
services:
  composer:
    image: composer:latest
    command: install
    networks:
        - backend
    volumes:
        - ./:/app
  php:
    image: php:7-fpm
    depends_on:
      - composer
    networks:
      - backend
    volumes:
      - ./:/code
  nginx:
    image: nginx:latest

    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./:/code
networks:
  frontend:
  backend: